{
 "title": "Agents",
 "time": { "from": "now-24h", "to": "now-1m" },
 "templating": {
  "list": [
   { "name": "cluster", "query": "influxdb" },
   {
    "name": "server",
    "query": "SHOW TAG VALUES FROM \"router\",\"agentserver\" WITH KEY = \"hostname\""
   }
  ]
 },
 "panels": [
  {
   "title": "Logged in agents and supervisors by tenant (agentserver view)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_tenant",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "tenant" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "router",
     "query": "SELECT mean(loggedAgents) FROM aggregated.tenant_agents WHERE $timeFilter GROUP BY time($interval), tenant",
     "select": [
      [
       { "params": [ "loggedAgents" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Logged in agents by tenant (router view)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_tenant",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "tenant" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "router",
     "query": "select mean(loggedAgents) from router where $timeFilter and loggedAgents > 0 and  \"hostname\" =~  /^$server$/ group by tenant, time($interval)",
     "select": [
      [
       { "params": [ "loggedAgents" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Logged in agents and supervisors by server (agentserver view)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "tenant" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "router",
     "query": "SELECT mean(loggedAgents) FROM aggregated.host_agents WHERE $timeFilter GROUP BY time($interval), hostname",
     "select": [
      [
       { "params": [ "loggedAgents" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Agent logouts due to connection loss",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_tenant",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "tenant" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT difference(max(s)) FROM (SELECT sum(totalConnectionLossLogouts) as s FROM \"agentserver\" WHERE $timeFilter GROUP BY tenant, time(10s, 1m)) WHERE $timeFilter GROUP BY tenant,time(15m)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}