[mikrotik]
router ansible_host=172.16.0.180 ansible_user=admin ansible_port=59222 mikrotik_config_file=config.rsc

# Пример для второго MikroTik:
# router2 ansible_host=192.0.2.10 ansible_user=admin ansible_port=22 mikrotik_config_file=router2.rsc

# Если используешь SSH-ключ, строка хоста может выглядеть так:
# router3 ansible_host=192.0.2.11 ansible_user=admin ansible_port=22 ansible_ssh_private_key_file=~/.ssh/id_rsa mikrotik_config_file=router3.rsc
